services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - /srv/docker/nginx/ssl_keys:/etc/nginx/ssl:ro
      - /srv/docker/nginx/client_certs:/etc/nginx/client_certs:ro
    networks:
      - webnet

networks:
  webnet:
    driver: bridge